language:
    - c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq intltool libgtk2.0-dev libnotify-dev libx11-dev libltdl-dev

script:
    - ./autogen.sh
    - ./configure
    - make
